# Rain in Australia - Post EDA
[https://www.kaggle.com/datasets/jsphyg/weather-dataset-rattle-package/data?select=weatherAUS.csv](https://www.kaggle.com/datasets/jsphyg/weather-dataset-rattle-package/data?select=weatherAUS.csv)

In [49]:
from joblib import load
import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer

In [71]:
def weather_predict_SGD(min_temp: float, max_temp: float, rainfall: float, wind_gust_speed: float, humidity: float, wind_speed: float, pressure: float, avg_temp: float, rain_today: bool, month: int, year: int):
    rain_today = 1 if rain_today else 0
    
    # Créer un DataFrame pour stocker les données d'entrée
    input_data = pd.DataFrame({
        'MinTemp': [min_temp],
        'MaxTemp': [max_temp],
        'Rainfall': [rainfall],
        'WindGustSpeed': [wind_gust_speed],
        'Humidity': [humidity],
        'WindSpeed': [wind_speed],
        'Pressure': [pressure],
        'Month': [month],
        'Temp': [avg_temp],
        'RainToday': [rain_today],
        'Year': [year]
    })
    
    # Charger le modèle
    loaded_model = load('ML_SGDClassifier.joblib')
    
    # Prédiction
    prediction = loaded_model.predict(input_data)
    return prediction

## Test 1

In [72]:
weather_predict_SGD(min_temp=13.4, max_temp=22.9, rainfall=0.6, wind_gust_speed=44, humidity=46.5, wind_speed=22, pressure=1007.4, avg_temp=19.35, rain_today=False, month=12, year=2008)

array([False])

## Test 2

In [73]:
weather_predict_SGD(min_temp=15.9, max_temp=21.7, rainfall=2.2, wind_gust_speed=31, humidity=90, wind_speed=14, pressure=1007.35, avg_temp=16.45, rain_today=True, month=12, year=2008)

array([False])

## Test 3

In [74]:
weather_predict_SGD(min_temp=15.9, max_temp=21.7, rainfall=2.2, wind_gust_speed=31, humidity=95, wind_speed=14, pressure=1007.35, avg_temp=16.45, rain_today=True, month=12, year=2008)

array([ True])